name: skillshare-data-science
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.3
  - pip=20.1.1
  - eli5=0.10.1
  - folium=0.11.0
  - jupyter=1.0.0
  - matplotlib==3.3.0
  - missingno=0.4.2
  - numpy=1.19.1
  - pandas=1.0.5
  - pandas-profiling=2.8.0
  - pandera=0.4.4
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.10.1
  - shap=0.35.0
  - sqlalchemy=1.3.18
  - voila=0.1.21
  - pip:
    - discover-feature-relationships==1.0.3
    - quilt==2.9.15
    - yellowbrick==1.1
