name: Rebuild Readme

on: 
  push:
    branches:
      - main
    paths-ignore:
      - README.md  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.x
      uses: actions/setup-python@master
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
    - name: Run Script
      run: |
        cd ${GITHUB_WORKSPACE}
        python ./.github/utils/create_readme.py
    - name: commit rendered README
      run: |-
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "Regenerate Readme"
        git push --all https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git